name: "🐛 Bug Report"
description: "If something isn't working as expected with Grain Social 🤔."
title: "[Bug]: "
labels: []
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report for Grain! Please fill out this form as completely as possible.

  - type: textarea
    attributes:
      label: Problem description
      description: |
        Please provide a detailed description of the issue you encountered with Grain.
      placeholder: |
        Describe the issue here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Provide the steps to reproduce the issue.
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Platform
      description: Which platform are you experiencing this issue on?
      options:
        - Web App
        - Mobile App
        - Both
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: |
        Describe the expected behavior here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        Please provide information about your environment, operating system, device, and any other relevant details.
      placeholder: |
        - Device: [e.g. iPhone 12, Pixel 5]
        - OS: [e.g. macOS 10.15.4, Windows 10, Browser]

  - type: textarea
    attributes:
      label: Possible solution
      description: "If you have suggestions on a fix for the bug."

  - type: textarea
    attributes:
      label: Additional context
      description: "Add any other context about the problem here. Or a screenshot if applicable."
